#!/bin/bash
#
# Wrapper to fix issues with ssh when the uid isn't in /etc/passwd
#
export NSS_WRAPPER_PASSWD=/tmp/passwd
export NSS_WRAPPER_GROUP=/tmp/group
echo "build:x:${BUILD_UID:-1000}:${BUILD_GID:-1000}::${WORKDIR:-/zynq7}:/bin/bash" > $NSS_WRAPPER_PASSWD
echo "build:x:${BUILD_GID:-1000}:" > $NSS_WRAPPER_GROUP
export LD_PRELOAD=libnss_wrapper.so
exec $@
